version: '3.9'

services:
  bot:
    build:
      dockerfile: ./Dockerfile
    command:
      - python
      - main.py
    restart: always
    logging:
      driver: 'json-file'
      options:
        max-file: '10'
        max-size: '200k'